-- ==============================================================================
-- 🚀 LAB MEMBERS - COMPLETE DATABASE SETUP & ADMIN SCHEMA (100% All-in-One)
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. جدول الحسابات والملفات الشخصية (Profiles Table)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  full_name TEXT,
  email TEXT,
  avatar_url TEXT,
  member_code INTEGER,
  last_seen_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- تسلسل تلقائي لأكواد العضوية
CREATE SEQUENCE IF NOT EXISTS public.member_code_seq START WITH 1 INCREMENT BY 1;
SELECT setval('public.member_code_seq', greatest(1, coalesce((SELECT max(member_code) FROM public.profiles), 0) + 1), false);

-- 2. تريجر إنشاء بروفايل تلقائي عند تسجيل أي مستخدم جديد (Auto Profile on Signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_next_code integer;
  v_name text;
begin
  v_next_code := nextval('public.member_code_seq');
  v_name := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    split_part(coalesce(new.email, ''), '@', 1),
    'Lab Member'
  );

  INSERT INTO public.profiles (id, username, full_name, email, avatar_url, member_code, last_seen_at)
  VALUES (
    new.id,
    lower(split_part(coalesce(new.email, new.id::text), '@', 1)),
    v_name,
    lower(new.email),
    coalesce(new.raw_user_meta_data->>'avatar_url', ''),
    v_next_code,
    now()
  )
  ON CONFLICT (id) DO UPDATE
  SET email = excluded.email,
      full_name = coalesce(public.profiles.full_name, excluded.full_name),
      updated_at = now();

  INSERT INTO public.user_identities (user_id, email)
  VALUES (new.id, lower(new.email))
  ON CONFLICT (user_id) DO UPDATE SET email = excluded.email;

  RETURN new;
end;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- إدخال المستخدمين الجدد فقط إذا لم يكونوا موجودين مسبقاً
INSERT INTO public.profiles (id, username, full_name, email, avatar_url, member_code, last_seen_at)
SELECT 
  u.id,
  lower(split_part(coalesce(u.email, u.id::text), '@', 1)),
  coalesce(u.raw_user_meta_data->>'full_name', u.raw_user_meta_data->>'name', split_part(coalesce(u.email, ''), '@', 1), 'User'),
  lower(u.email),
  coalesce(u.raw_user_meta_data->>'avatar_url', ''),
  (coalesce((SELECT max(member_code) FROM public.profiles), 0) + row_number() over ()),
  now()
FROM auth.users u
WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = u.id);

-- تحديث تسلسل أكواد العضوية
SELECT setval('public.member_code_seq', greatest(1, coalesce((SELECT max(member_code) FROM public.profiles), 0) + 1), false);

-- 3. جدول هويات المستخدمين (User Identities)
CREATE TABLE IF NOT EXISTS public.user_identities (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL
);

INSERT INTO public.user_identities (user_id, email)
SELECT id, lower(email) FROM auth.users WHERE email IS NOT NULL
ON CONFLICT (user_id) DO UPDATE SET email = excluded.email;

-- 4. جدول الرسائل والمحادثات (Messages Table)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS messages_sender_receiver_idx ON public.messages (sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON public.messages (created_at DESC);

-- 5. جدول طلبات الصداقة (Friend Requests Table)
CREATE TABLE IF NOT EXISTS public.friend_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_email TEXT,
  receiver_email TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT friend_requests_no_self CHECK (sender_id <> receiver_id)
);

CREATE INDEX IF NOT EXISTS friend_requests_sender_email_idx ON public.friend_requests (lower(sender_email));
CREATE INDEX IF NOT EXISTS friend_requests_receiver_email_idx ON public.friend_requests (lower(receiver_email));
CREATE INDEX IF NOT EXISTS friend_requests_pair_idx ON public.friend_requests (least(sender_id, receiver_id), greatest(sender_id, receiver_id));

-- 6. جدول الحظر الإداري (Admin User Moderation)
CREATE TABLE IF NOT EXISTS public.admin_user_moderation (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  is_banned BOOLEAN DEFAULT false,
  ban_reason TEXT DEFAULT '',
  banned_by UUID REFERENCES auth.users(id),
  banned_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. جدول التعميمات والإعلانات العامة (Broadcast Announcements)
CREATE TABLE IF NOT EXISTS public.admin_broadcasts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_name TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'warning', 'urgent', 'success')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 8. جدول حظر رسائل المشرفين (Admin Message Blocks)
CREATE TABLE IF NOT EXISTS public.admin_message_blocks (
  admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (admin_id, user_id),
  CONSTRAINT admin_message_blocks_no_self CHECK (admin_id <> user_id)
);

-- 9. جدول الأجهزة المعروفة للمستخدمين (Known Devices)
CREATE TABLE IF NOT EXISTS public.user_known_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_fid TEXT NOT NULL,
  device_name TEXT NOT NULL,
  device_type TEXT NOT NULL DEFAULT 'desktop',
  os_name TEXT,
  browser_name TEXT,
  ip_address TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_known_devices_uniq UNIQUE (user_id, device_fid)
);

-- 10. جدول سجلات تسجيل الدخول الأمنية (Login Security Logs)
CREATE TABLE IF NOT EXISTS public.user_login_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_fid TEXT NOT NULL,
  device_name TEXT NOT NULL,
  device_type TEXT NOT NULL DEFAULT 'desktop',
  os_name TEXT,
  browser_name TEXT,
  ip_address TEXT,
  is_new_device BOOLEAN DEFAULT false,
  logged_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- 🔒 دوال الأمان والباك إند (RPC & Stored Procedures)
-- ==============================================================================

-- دالة التحقق من أن المستدعي هو المشرف
CREATE OR REPLACE FUNCTION public.assert_admin_caller()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  caller_email text;
  is_admin_flag boolean;
begin
  caller_email := lower(trim(coalesce(auth.jwt()->>'email', '')));
  is_admin_flag := coalesce((auth.jwt()->'user_metadata'->>'is_admin')::boolean, false);

  IF caller_email <> 'ywsfw3778@gmail.com' AND NOT is_admin_flag THEN
    RAISE EXCEPTION 'Unauthorized: Only platform administrators can execute this function.';
  END IF;
  return caller_email;
end;
$$;

-- دالة تحديث بيانات وصورة المستخدم بواسطة الإدارة
CREATE OR REPLACE FUNCTION public.admin_update_user_profile(
  target_user_id UUID,
  new_name TEXT,
  new_member_code INTEGER,
  new_avatar_url TEXT DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();

  UPDATE public.profiles
  SET full_name = coalesce(nullif(trim(new_name), ''), full_name),
      member_code = coalesce(new_member_code, member_code),
      avatar_url = CASE 
        WHEN new_avatar_url = '__REMOVE__' THEN NULL
        WHEN new_avatar_url IS NOT NULL THEN new_avatar_url
        ELSE avatar_url
      END,
      updated_at = now()
  WHERE id = target_user_id;

  RETURN true;
end;
$$;

-- دالة حظر / فك حظر مستخدم
CREATE OR REPLACE FUNCTION public.admin_set_user_ban(
  target_user_id UUID,
  ban_status BOOLEAN,
  reason_text TEXT DEFAULT ''
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();

  INSERT INTO public.admin_user_moderation (user_id, is_banned, ban_reason, banned_by, banned_at, updated_at)
  VALUES (target_user_id, ban_status, reason_text, auth.uid(), now(), now())
  ON CONFLICT (user_id) DO UPDATE
  SET is_banned = excluded.is_banned,
      ban_reason = excluded.ban_reason,
      banned_by = auth.uid(),
      updated_at = now();

  RETURN true;
end;
$$;

-- دالة إحصائيات لوحة التحكم الشاملة
CREATE OR REPLACE FUNCTION public.admin_get_dashboard_stats()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_total_users integer;
  v_online_users integer;
  v_total_messages integer;
  v_total_friend_requests integer;
  v_total_voice_messages integer;
  v_total_image_messages integer;
  v_banned_users integer;
begin
  v_admin := public.assert_admin_caller();

  SELECT count(*) INTO v_total_users FROM public.profiles;
  SELECT count(*) INTO v_online_users FROM public.profiles WHERE last_seen_at >= (now() - interval '5 minutes');
  SELECT count(*) INTO v_total_messages FROM public.messages;
  SELECT count(*) INTO v_total_voice_messages FROM public.messages WHERE content LIKE '[voice]%' OR content LIKE '[audio]%';
  SELECT count(*) INTO v_total_image_messages FROM public.messages WHERE content LIKE '[image]%';
  SELECT count(*) INTO v_total_friend_requests FROM public.friend_requests;
  SELECT count(*) INTO v_banned_users FROM public.admin_user_moderation WHERE is_banned = true;

  RETURN json_build_object(
    'total_users', coalesce(v_total_users, 0),
    'online_users', coalesce(v_online_users, 0),
    'total_messages', coalesce(v_total_messages, 0),
    'total_voice_messages', coalesce(v_total_voice_messages, 0),
    'total_image_messages', coalesce(v_total_image_messages, 0),
    'total_friend_requests', coalesce(v_total_friend_requests, 0),
    'banned_users', coalesce(v_banned_users, 0),
    'server_time', now()
  );
end;
$$;

-- دالة جلب قائمة كل المستخدمين للإدارة
CREATE OR REPLACE FUNCTION public.admin_get_all_users()
RETURNS TABLE (
  id UUID,
  email TEXT,
  username TEXT,
  full_name TEXT,
  avatar_url TEXT,
  member_code INTEGER,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  is_admin BOOLEAN,
  is_banned BOOLEAN,
  ban_reason TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();

  RETURN QUERY
  SELECT 
    p.id,
    coalesce(p.email, u.email) as email,
    p.username,
    coalesce(p.full_name, p.username, 'User') as full_name,
    p.avatar_url,
    p.member_code,
    p.last_seen_at,
    u.created_at,
    (lower(coalesce(p.email, u.email, '')) = 'ywsfw3778@gmail.com' 
     OR coalesce((u.raw_user_meta_data->>'is_admin')::boolean, false) = true) as is_admin,
    coalesce(m.is_banned, false) as is_banned,
    coalesce(m.ban_reason, '') as ban_reason
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  LEFT JOIN public.admin_user_moderation m ON m.user_id = u.id
  ORDER BY coalesce(p.last_seen_at, u.created_at) DESC;
end;
$$;

-- دالة إنشاء إعلان جماعي
CREATE OR REPLACE FUNCTION public.admin_create_broadcast(
  p_title TEXT,
  p_content TEXT,
  p_type TEXT DEFAULT 'info'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_sender_name text;
  v_broadcast_id UUID;
begin
  v_admin := public.assert_admin_caller();

  SELECT coalesce(full_name, username, 'الإدارة') INTO v_sender_name
  FROM public.profiles WHERE id = auth.uid();

  INSERT INTO public.admin_broadcasts (sender_id, sender_name, title, content, type)
  VALUES (auth.uid(), coalesce(v_sender_name, 'الإدارة'), p_title, p_content, p_type)
  RETURNING id INTO v_broadcast_id;

  RETURN v_broadcast_id;
end;
$$;

-- دالة تسجيل الجهاز وفحص هل هو جهاز جديد لإرسال إشعار الأمان (Device Registration & New Device Check)
CREATE OR REPLACE FUNCTION public.register_device_and_check_is_new(
  p_device_fid TEXT,
  p_device_name TEXT,
  p_device_type TEXT DEFAULT 'desktop',
  p_os TEXT DEFAULT '',
  p_browser TEXT DEFAULT '',
  p_ip TEXT DEFAULT ''
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_user_id UUID;
  v_exists boolean;
begin
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN false;
  END IF;

  -- فحص هل البصمة مسجلة للمستخدم مسبقاً
  SELECT EXISTS (
    SELECT 1 FROM public.user_known_devices
    WHERE user_id = v_user_id AND device_fid = p_device_fid
  ) INTO v_exists;

  IF NOT v_exists THEN
    -- تسجيل الجهاز الجديد لأول مرة
    INSERT INTO public.user_known_devices (user_id, device_fid, device_name, device_type, os_name, browser_name, ip_address, first_seen_at, last_seen_at)
    VALUES (v_user_id, p_device_fid, p_device_name, p_device_type, p_os, p_browser, p_ip, now(), now())
    ON CONFLICT (user_id, device_fid) DO UPDATE
    SET last_seen_at = now(),
        device_name = excluded.device_name,
        ip_address = coalesce(excluded.ip_address, public.user_known_devices.ip_address);

    -- تسجيل سجل دخول جديد
    INSERT INTO public.user_login_logs (user_id, device_fid, device_name, device_type, os_name, browser_name, ip_address, is_new_device, logged_at)
    VALUES (v_user_id, p_device_fid, p_device_name, p_device_type, p_os, p_browser, p_ip, true, now());

    RETURN true; -- جهاز جديد لأول مرة -> يتطلب إشعار أمان
  ELSE
    -- تحديث وقت آخر ظهور للجهاز
    UPDATE public.user_known_devices
    SET last_seen_at = now(),
        device_name = coalesce(nullif(p_device_name, ''), device_name),
        ip_address = coalesce(nullif(p_ip, ''), ip_address)
    WHERE user_id = v_user_id AND device_fid = p_device_fid;

    INSERT INTO public.user_login_logs (user_id, device_fid, device_name, device_type, os_name, browser_name, ip_address, is_new_device, logged_at)
    VALUES (v_user_id, p_device_fid, p_device_name, p_device_type, p_os, p_browser, p_ip, false, now());

    RETURN false; -- جهاز معروف سابقاً
  END IF;
end;
$$;

-- دالة تعيين أو إلغاء رتبة المشرف لمستخدم (Set/Unset Admin Role)
CREATE OR REPLACE FUNCTION public.admin_set_user_admin(
  target_user_id UUID,
  is_admin_status BOOLEAN
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_target_email text;
begin
  v_admin := public.assert_admin_caller();

  SELECT lower(coalesce(email, '')) INTO v_target_email
  FROM auth.users
  WHERE id = target_user_id;

  IF v_target_email = 'ywsfw3778@gmail.com' AND NOT is_admin_status THEN
    RAISE EXCEPTION 'Cannot demote the primary owner.';
  END IF;

  UPDATE auth.users
  SET raw_user_meta_data = jsonb_set(
    coalesce(raw_user_meta_data, '{}'::jsonb),
    '{is_admin}',
    to_jsonb(is_admin_status)
  )
  WHERE id = target_user_id;

  BEGIN
    UPDATE public.profiles
    SET is_admin = is_admin_status,
        updated_at = now()
    WHERE id = target_user_id;
  EXCEPTION WHEN undefined_column THEN
    NULL;
  END;

  RETURN true;
end;
$$;

-- دالة حذف حساب مستخدم نهائياً بكافة بياناته (Delete User Completely)
CREATE OR REPLACE FUNCTION public.admin_delete_user(
  target_user_id UUID
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_target_email text;
begin
  v_admin := public.assert_admin_caller();

  SELECT lower(coalesce(email, '')) INTO v_target_email
  FROM auth.users
  WHERE id = target_user_id;

  IF v_target_email = 'ywsfw3778@gmail.com' THEN
    RAISE EXCEPTION 'Cannot delete the primary owner account.';
  END IF;

  DELETE FROM public.messages WHERE sender_id = target_user_id OR receiver_id = target_user_id;
  DELETE FROM public.friend_requests WHERE sender_id = target_user_id OR receiver_id = target_user_id;
  DELETE FROM public.admin_user_moderation WHERE user_id = target_user_id;
  DELETE FROM public.admin_message_blocks WHERE admin_id = target_user_id OR user_id = target_user_id;
  DELETE FROM public.user_identities WHERE user_id = target_user_id;
  DELETE FROM public.profiles WHERE id = target_user_id;
  DELETE FROM auth.users WHERE id = target_user_id;

  RETURN true;
end;
$$;

-- ==============================================================================
-- 🔐 سياسات الحماية (Row Level Security - RLS)
-- ==============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_user_moderation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_message_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_known_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_login_logs ENABLE ROW LEVEL SECURITY;

-- سياسات الأجهزة المعروفة وسجلات الدخول (User Devices & Logs RLS)
DROP POLICY IF EXISTS "user_known_devices_self" ON public.user_known_devices;
CREATE POLICY "user_known_devices_self" ON public.user_known_devices FOR ALL TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "user_login_logs_self" ON public.user_login_logs;
CREATE POLICY "user_login_logs_self" ON public.user_login_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- منح صلاحيات الاستدعاء
GRANT EXECUTE ON FUNCTION public.register_device_and_check_is_new(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_admin(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(UUID) TO authenticated;

-- 1. سياسات البروفايلات (Profiles RLS - تسمح للمشرف بتعديل كل الحسابات)
DROP POLICY IF EXISTS "profiles_select_all" ON public.profiles;
CREATE POLICY "profiles_select_all" ON public.profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "profiles_insert_self" ON public.profiles;
CREATE POLICY "profiles_insert_self" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_admin_or_self" ON public.profiles;
CREATE POLICY "profiles_update_admin_or_self" ON public.profiles FOR UPDATE TO authenticated
USING (
  auth.uid() = id
  OR lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com'
  OR coalesce((auth.jwt()->'user_metadata'->>'is_admin')::boolean, false) = true
)
WITH CHECK (
  auth.uid() = id
  OR lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com'
  OR coalesce((auth.jwt()->'user_metadata'->>'is_admin')::boolean, false) = true
);

-- 2. سياسات الرسائل (Messages RLS)
DROP POLICY IF EXISTS "messages_select_all_related" ON public.messages;
CREATE POLICY "messages_select_all_related" ON public.messages FOR SELECT TO authenticated
USING (
  auth.uid() = sender_id 
  OR auth.uid() = receiver_id
  OR lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com'
);

DROP POLICY IF EXISTS "messages_insert_user" ON public.messages;
CREATE POLICY "messages_insert_user" ON public.messages FOR INSERT TO authenticated
WITH CHECK (
  auth.uid() = sender_id
  AND NOT EXISTS (
    SELECT 1 FROM public.admin_user_moderation aum
    WHERE aum.user_id = auth.uid() AND aum.is_banned = true
  )
);

DROP POLICY IF EXISTS "messages_delete_owner_or_admin" ON public.messages;
CREATE POLICY "messages_delete_owner_or_admin" ON public.messages FOR DELETE TO authenticated
USING (
  auth.uid() = sender_id 
  OR auth.uid() = receiver_id
  OR lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com'
);

-- 3. سياسات الحظر والتعميمات
DROP POLICY IF EXISTS "admin_user_moderation_read" ON public.admin_user_moderation;
CREATE POLICY "admin_user_moderation_read" ON public.admin_user_moderation FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_user_moderation_admin" ON public.admin_user_moderation;
CREATE POLICY "admin_user_moderation_admin" ON public.admin_user_moderation FOR ALL TO authenticated
USING (lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com');

DROP POLICY IF EXISTS "admin_broadcasts_select" ON public.admin_broadcasts;
CREATE POLICY "admin_broadcasts_select" ON public.admin_broadcasts FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_broadcasts_admin" ON public.admin_broadcasts;
CREATE POLICY "admin_broadcasts_admin" ON public.admin_broadcasts FOR ALL TO authenticated
USING (lower(coalesce(auth.jwt()->>'email', '')) = 'ywsfw3778@gmail.com');

DROP POLICY IF EXISTS "user_identities_all" ON public.user_identities;
CREATE POLICY "user_identities_all" ON public.user_identities FOR SELECT TO authenticated USING (true);

-- 4. إعطاء الصلاحيات لجميع الدوال والجداول (Grants)
GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated, anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO authenticated, anon;

-- ==============================================================================
-- 📁 مجلدات التخزين السحابي (Storage Buckets for Avatars & Voices)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true), ('voices', 'voices', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "avatars_public_select" ON storage.objects;
CREATE POLICY "avatars_public_select" ON storage.objects FOR SELECT TO authenticated, anon
USING (bucket_id = 'avatars' OR bucket_id = 'voices');

DROP POLICY IF EXISTS "avatars_authenticated_insert" ON storage.objects;
CREATE POLICY "avatars_authenticated_insert" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'avatars' OR bucket_id = 'voices');

DROP POLICY IF EXISTS "avatars_authenticated_update" ON storage.objects;
CREATE POLICY "avatars_authenticated_update" ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'avatars' OR bucket_id = 'voices');
