-- ==============================================================================
-- 🚀 LAB MEMBERS - PRODUCTION-HARDENED DATABASE SETUP & SECURITY POLICIES
-- ==============================================================================
-- IMPORTANT: Run SECURITY_HARDENING.sql after this setup (and after the friend
-- request rebuild) to apply the final routine and Storage permission lockdown.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. جدول الأدوار الإدارية المحمية
CREATE TABLE IF NOT EXISTS public.admin_roles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin', 'moderator')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id)
);

-- 2. جدول الحسابات والملفات الشخصية
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  full_name TEXT,
  email TEXT,
  avatar_url TEXT,
  member_code INTEGER,
  last_seen_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS public.member_code_seq START WITH 1 INCREMENT BY 1;
SELECT setval('public.member_code_seq', greatest(1, coalesce((SELECT max(member_code) FROM public.profiles), 0) + 1), false);

-- 3. جدول هويات المستخدمين
CREATE TABLE IF NOT EXISTS public.user_identities (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL
);

-- 4. جدول الرسائل
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS messages_sender_receiver_idx ON public.messages (sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON public.messages (created_at DESC);

-- 5. جدول طلبات الصداقة
CREATE TABLE IF NOT EXISTS public.friend_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_email TEXT,
  receiver_email TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT friend_requests_no_self CHECK (sender_id <> receiver_id)
);

CREATE INDEX IF NOT EXISTS friend_requests_sender_email_idx ON public.friend_requests (lower(sender_email));
CREATE INDEX IF NOT EXISTS friend_requests_receiver_email_idx ON public.friend_requests (lower(receiver_email));
CREATE INDEX IF NOT EXISTS friend_requests_pair_idx ON public.friend_requests (least(sender_id, receiver_id), greatest(sender_id, receiver_id));

-- 6. جدول الحظر الإداري
CREATE TABLE IF NOT EXISTS public.admin_user_moderation (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  is_banned BOOLEAN DEFAULT false,
  ban_reason TEXT DEFAULT '',
  banned_by UUID REFERENCES auth.users(id),
  banned_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. جدول الإعلانات
CREATE TABLE IF NOT EXISTS public.admin_broadcasts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_name TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'warning', 'urgent', 'success')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 8. جدول حظر رسائل المشرفين
CREATE TABLE IF NOT EXISTS public.admin_message_blocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (admin_id, user_id)
);

-- 9. جدول الأجهزة المعروفة
CREATE TABLE IF NOT EXISTS public.user_known_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_fingerprint TEXT NOT NULL,
  browser_name TEXT,
  os_name TEXT,
  ip_address TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_trusted BOOLEAN NOT NULL DEFAULT true,
  UNIQUE(user_id, device_fingerprint)
);

-- 10. جدول سجلات الدخول
CREATE TABLE IF NOT EXISTS public.user_login_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_fingerprint TEXT,
  browser_name TEXT,
  os_name TEXT,
  ip_address TEXT,
  country TEXT,
  city TEXT,
  is_new_device BOOLEAN NOT NULL DEFAULT false,
  logged_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- حذف الدوال القديمة لتفادي أخطاء تغيير أنواع المخرجات (DROP OLD FUNCTIONS)
DROP FUNCTION IF EXISTS public.get_chat_messages(UUID, INT) CASCADE;
DROP FUNCTION IF EXISTS public.get_chat_messages(UUID, INTEGER) CASCADE;
DROP FUNCTION IF EXISTS public.get_chat_messages(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_chat_messages_for_email(TEXT, UUID, INT) CASCADE;
DROP FUNCTION IF EXISTS public.get_chat_messages_for_email(TEXT, UUID, INTEGER) CASCADE;
DROP FUNCTION IF EXISTS public.get_inbox_contacts() CASCADE;
DROP FUNCTION IF EXISTS public.get_inbox_contacts_for_email(TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_get_all_users() CASCADE;
DROP FUNCTION IF EXISTS public.admin_get_dashboard_stats() CASCADE;
DROP FUNCTION IF EXISTS public.admin_set_user_admin(UUID, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS public.admin_set_user_ban(UUID, BOOLEAN, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_update_user_profile(UUID, TEXT, INTEGER, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_create_broadcast(TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_purge_all_messages() CASCADE;
DROP FUNCTION IF EXISTS public.admin_delete_user(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.register_device_and_check_is_new(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) CASCADE;

-- 1. تأكيد كل الحسابات الحالية تلقائياً
UPDATE auth.users 
SET email_confirmed_at = COALESCE(email_confirmed_at, now()),
    confirmed_at = COALESCE(confirmed_at, now())
WHERE email_confirmed_at IS NULL;

-- 2. تريجر تأكيد أي إيميل جديد تلقائياً في لحظة التسجيل بدون طلب كود أو رسائل
CREATE OR REPLACE FUNCTION public.auto_confirm_user_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  NEW.email_confirmed_at := COALESCE(NEW.email_confirmed_at, now());
  NEW.confirmed_at := COALESCE(NEW.confirmed_at, now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_auto_confirm_user_email ON auth.users;
CREATE TRIGGER tr_auto_confirm_user_email
BEFORE INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.auto_confirm_user_email();

-- تريجر إنشاء بروفايل تلقائي عند تسجيل أي مستخدم جديد (متوافق 100% مع Google OAuth)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_next_code integer;
  v_name text;
  v_avatar text;
  v_base_username text;
  v_username text;
begin
  BEGIN
    v_next_code := nextval('public.member_code_seq');
  EXCEPTION WHEN OTHERS THEN
    v_next_code := (coalesce((SELECT max(member_code) FROM public.profiles), 0) + 1);
  END;

  v_name := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    split_part(coalesce(new.email, ''), '@', 1),
    'Lab Member'
  );

  v_avatar := coalesce(
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'picture',
    new.raw_user_meta_data->>'avatar',
    ''
  );

  v_base_username := lower(regexp_replace(split_part(coalesce(new.email, new.id::text), '@', 1), '[^a-zA-Z0-9_]', '', 'g'));
  IF v_base_username IS NULL OR v_base_username = '' THEN
    v_base_username := 'user_' || substr(new.id::text, 1, 6);
  END IF;

  v_username := v_base_username;
  IF EXISTS (SELECT 1 FROM public.profiles WHERE username = v_username AND id <> new.id) THEN
    v_username := v_base_username || '_' || v_next_code;
  END IF;

  BEGIN
    INSERT INTO public.profiles (id, username, full_name, email, avatar_url, member_code, last_seen_at)
    VALUES (
      new.id,
      v_username,
      v_name,
      lower(coalesce(new.email, '')),
      v_avatar,
      v_next_code,
      now()
    )
    ON CONFLICT (id) DO UPDATE
    SET email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name),
        avatar_url = CASE WHEN public.profiles.avatar_url IS NULL OR public.profiles.avatar_url = '' THEN excluded.avatar_url ELSE public.profiles.avatar_url END,
        updated_at = now();
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO public.profiles (id, username, full_name, email, avatar_url, member_code, last_seen_at)
    VALUES (
      new.id,
      'user_' || substr(new.id::text, 1, 8),
      v_name,
      lower(coalesce(new.email, '')),
      v_avatar,
      v_next_code,
      now()
    )
    ON CONFLICT (id) DO UPDATE
    SET email = excluded.email,
        updated_at = now();
  END;

  BEGIN
    INSERT INTO public.user_identities (user_id, email)
    VALUES (new.id, lower(coalesce(new.email, '')))
    ON CONFLICT (user_id) DO UPDATE SET email = excluded.email;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  IF lower(trim(coalesce(new.email, ''))) = 'ywsfw3778@gmail.com' THEN
    BEGIN
      INSERT INTO public.admin_roles (user_id, role)
      VALUES (new.id, 'superadmin')
      ON CONFLICT (user_id) DO NOTHING;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;

  RETURN new;
end;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- إدخال المستخدمين الحاليين في profiles و user_identities و admin_roles
INSERT INTO public.profiles (id, username, full_name, email, avatar_url, member_code, last_seen_at)
SELECT 
  u.id,
  lower(split_part(coalesce(u.email, u.id::text), '@', 1)),
  coalesce(u.raw_user_meta_data->>'full_name', u.raw_user_meta_data->>'name', split_part(coalesce(u.email, ''), '@', 1), 'User'),
  lower(u.email),
  coalesce(u.raw_user_meta_data->>'avatar_url', ''),
  (coalesce((SELECT max(member_code) FROM public.profiles), 0) + row_number() over ()),
  now()
FROM auth.users u
WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = u.id);

INSERT INTO public.user_identities (user_id, email)
SELECT id, lower(email) FROM auth.users WHERE email IS NOT NULL
ON CONFLICT (user_id) DO UPDATE SET email = excluded.email;

INSERT INTO public.admin_roles (user_id, role)
SELECT id, 'superadmin' FROM auth.users WHERE lower(email) = 'ywsfw3778@gmail.com'
ON CONFLICT (user_id) DO NOTHING;

-- دالة التحقق من المشرفين
CREATE OR REPLACE FUNCTION public.is_admin_caller()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  caller_email text;
  caller_id uuid;
begin
  caller_id := auth.uid();
  caller_email := lower(trim(coalesce(auth.jwt()->>'email', '')));
  
  IF caller_email = 'ywsfw3778@gmail.com' THEN
    RETURN true;
  END IF;
  
  IF caller_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.admin_roles WHERE user_id = caller_id
  ) THEN
    RETURN true;
  END IF;
  
  RETURN false;
end;
$$;

CREATE OR REPLACE FUNCTION public.assert_admin_caller()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  caller_email text;
begin
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'Unauthorized: Only platform administrators can execute this function.';
  END IF;
  caller_email := lower(trim(coalesce(auth.jwt()->>'email', '')));
  RETURN caller_email;
end;
$$;

-- دوال الإدارة
CREATE OR REPLACE FUNCTION public.admin_get_dashboard_stats()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_total_users integer;
  v_online_users integer;
  v_total_messages integer;
  v_total_friend_requests integer;
  v_total_voice_messages integer;
  v_total_image_messages integer;
  v_banned_users integer;
  v_stats json;
begin
  v_admin := public.assert_admin_caller();

  SELECT count(*) INTO v_total_users FROM public.profiles;
  SELECT count(*) INTO v_online_users FROM public.profiles WHERE last_seen_at >= (now() - interval '5 minutes');
  SELECT count(*) INTO v_total_messages FROM public.messages;
  SELECT count(*) INTO v_total_voice_messages FROM public.messages WHERE content LIKE '[voice]%' OR content LIKE '[audio]%';
  SELECT count(*) INTO v_total_image_messages FROM public.messages WHERE content LIKE '[image]%';
  SELECT count(*) INTO v_total_friend_requests FROM public.friend_requests;
  SELECT count(*) INTO v_banned_users FROM public.admin_user_moderation WHERE is_banned = true;

  v_stats := json_build_object(
    'total_users', coalesce(v_total_users, 0),
    'online_users', coalesce(v_online_users, 0),
    'total_messages', coalesce(v_total_messages, 0),
    'total_voice_messages', coalesce(v_total_voice_messages, 0),
    'total_image_messages', coalesce(v_total_image_messages, 0),
    'total_friend_requests', coalesce(v_total_friend_requests, 0),
    'banned_users', coalesce(v_banned_users, 0),
    'server_time', now()
  );

  return v_stats;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_get_all_users()
RETURNS TABLE (
  id UUID,
  email TEXT,
  username TEXT,
  full_name TEXT,
  avatar_url TEXT,
  member_code INTEGER,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  is_admin BOOLEAN,
  is_banned BOOLEAN,
  ban_reason TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();

  RETURN QUERY
  SELECT 
    p.id,
    coalesce(p.email, u.email) as email,
    p.username,
    coalesce(p.full_name, p.username, 'User') as full_name,
    p.avatar_url,
    p.member_code,
    p.last_seen_at,
    u.created_at,
    (lower(coalesce(p.email, u.email, '')) = 'ywsfw3778@gmail.com' 
     OR EXISTS (SELECT 1 FROM public.admin_roles ar WHERE ar.user_id = u.id)) as is_admin,
    coalesce(m.is_banned, false) as is_banned,
    coalesce(m.ban_reason, '') as ban_reason
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  LEFT JOIN public.admin_user_moderation m ON m.user_id = u.id
  ORDER BY coalesce(p.last_seen_at, u.created_at) DESC;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_ban(
  target_user_id UUID,
  ban_status BOOLEAN,
  reason_text TEXT DEFAULT ''
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_target_email text;
begin
  v_admin := public.assert_admin_caller();

  SELECT lower(coalesce(email, '')) INTO v_target_email FROM auth.users WHERE id = target_user_id;
  IF v_target_email = 'ywsfw3778@gmail.com' THEN
    RAISE EXCEPTION 'Cannot ban the primary platform owner.';
  END IF;

  INSERT INTO public.admin_user_moderation (user_id, is_banned, ban_reason, banned_by, banned_at, updated_at)
  VALUES (target_user_id, ban_status, reason_text, auth.uid(), now(), now())
  ON CONFLICT (user_id) DO UPDATE
  SET is_banned = excluded.is_banned,
      ban_reason = excluded.ban_reason,
      banned_by = auth.uid(),
      updated_at = now();

  RETURN true;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_admin(
  target_user_id UUID,
  is_admin_status BOOLEAN
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_target_email text;
begin
  v_admin := public.assert_admin_caller();

  SELECT lower(coalesce(email, '')) INTO v_target_email
  FROM auth.users
  WHERE id = target_user_id;

  IF v_target_email = 'ywsfw3778@gmail.com' AND NOT is_admin_status THEN
    RAISE EXCEPTION 'Cannot demote the primary owner.';
  END IF;

  IF is_admin_status THEN
    INSERT INTO public.admin_roles (user_id, role, created_by)
    VALUES (target_user_id, 'admin', auth.uid())
    ON CONFLICT (user_id) DO NOTHING;
  ELSE
    DELETE FROM public.admin_roles WHERE user_id = target_user_id;
  END IF;

  RETURN true;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_user_profile(
  target_user_id UUID,
  new_name TEXT,
  new_member_code INTEGER,
  new_avatar_url TEXT DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();

  UPDATE public.profiles
  SET full_name = coalesce(nullif(trim(new_name), ''), full_name),
      member_code = coalesce(new_member_code, member_code),
      avatar_url = CASE 
        WHEN new_avatar_url = '__REMOVE__' THEN NULL
        WHEN new_avatar_url IS NOT NULL THEN new_avatar_url
        ELSE avatar_url
      END
  WHERE id = target_user_id;

  RETURN true;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_create_broadcast(
  p_title TEXT,
  p_content TEXT,
  p_type TEXT DEFAULT 'info'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_sender_name text;
  v_broadcast_id UUID;
begin
  v_admin := public.assert_admin_caller();

  SELECT coalesce(full_name, username, 'الإدارة') INTO v_sender_name
  FROM public.profiles WHERE id = auth.uid();

  INSERT INTO public.admin_broadcasts (sender_id, sender_name, title, content, type)
  VALUES (auth.uid(), coalesce(v_sender_name, 'الإدارة'), p_title, p_content, p_type)
  RETURNING id INTO v_broadcast_id;

  RETURN v_broadcast_id;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_purge_all_messages()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
begin
  v_admin := public.assert_admin_caller();
  TRUNCATE TABLE public.messages RESTART IDENTITY CASCADE;
  RETURN true;
end;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_user(
  target_user_id UUID
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_admin text;
  v_target_email text;
begin
  v_admin := public.assert_admin_caller();

  SELECT lower(coalesce(email, '')) INTO v_target_email
  FROM auth.users
  WHERE id = target_user_id;

  IF v_target_email = 'ywsfw3778@gmail.com' THEN
    RAISE EXCEPTION 'Cannot delete the primary owner account.';
  END IF;

  DELETE FROM public.messages WHERE sender_id = target_user_id OR receiver_id = target_user_id;
  DELETE FROM public.friend_requests WHERE sender_id = target_user_id OR receiver_id = target_user_id;
  DELETE FROM public.admin_user_moderation WHERE user_id = target_user_id;
  DELETE FROM public.admin_message_blocks WHERE admin_id = target_user_id OR user_id = target_user_id;
  DELETE FROM public.admin_roles WHERE user_id = target_user_id;
  DELETE FROM public.user_identities WHERE user_id = target_user_id;
  DELETE FROM public.profiles WHERE id = target_user_id;
  DELETE FROM auth.users WHERE id = target_user_id;

  RETURN true;
end;
$$;

CREATE OR REPLACE FUNCTION public.register_device_and_check_is_new(
  p_device_fingerprint TEXT,
  p_browser_name TEXT DEFAULT NULL,
  p_os_name TEXT DEFAULT NULL,
  p_ip_address TEXT DEFAULT NULL,
  p_country TEXT DEFAULT NULL,
  p_city TEXT DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_user_id UUID;
  v_is_new BOOLEAN := false;
  v_existing_id UUID;
begin
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Not authenticated');
  END IF;

  SELECT id INTO v_existing_id
  FROM public.user_known_devices
  WHERE user_id = v_user_id AND device_fingerprint = p_device_fingerprint;

  IF v_existing_id IS NULL THEN
    v_is_new := true;
    INSERT INTO public.user_known_devices (user_id, device_fingerprint, browser_name, os_name, ip_address, first_seen_at, last_seen_at)
    VALUES (v_user_id, p_device_fingerprint, p_browser_name, p_os_name, p_ip_address, now(), now());
  ELSE
    UPDATE public.user_known_devices
    SET last_seen_at = now(),
        browser_name = coalesce(p_browser_name, browser_name),
        os_name = coalesce(p_os_name, os_name),
        ip_address = coalesce(p_ip_address, ip_address)
    WHERE id = v_existing_id;
  END IF;

  INSERT INTO public.user_login_logs (user_id, device_fingerprint, browser_name, os_name, ip_address, country, city, is_new_device, logged_at)
  VALUES (v_user_id, p_device_fingerprint, p_browser_name, p_os_name, p_ip_address, p_country, p_city, v_is_new, now());

  RETURN json_build_object('success', true, 'is_new_device', v_is_new, 'user_id', v_user_id);
end;
$$;

CREATE OR REPLACE FUNCTION public.get_chat_messages(
  partner_user_id UUID,
  result_limit INT DEFAULT 500
)
RETURNS TABLE (
  id BIGINT,
  sender_id UUID,
  receiver_id UUID,
  content TEXT,
  created_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_me UUID;
begin
  v_me := auth.uid();
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  RETURN QUERY
  SELECT m.id, m.sender_id, m.receiver_id, m.content, m.created_at, m.read_at
  FROM public.messages m
  WHERE (m.sender_id = v_me AND m.receiver_id = partner_user_id)
     OR (m.sender_id = partner_user_id AND m.receiver_id = v_me)
  ORDER BY m.created_at ASC
  LIMIT coalesce(result_limit, 500);
end;
$$;

CREATE OR REPLACE FUNCTION public.get_inbox_contacts()
RETURNS TABLE (
  partner_id UUID,
  name TEXT,
  username TEXT,
  email TEXT,
  avatar_url TEXT,
  member_code INTEGER,
  last_seen_at TIMESTAMPTZ,
  last_content TEXT,
  last_created_at TIMESTAMPTZ,
  unread_count BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
declare
  v_me UUID;
begin
  v_me := auth.uid();
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  RETURN QUERY
  WITH partner_msgs AS (
    SELECT 
      CASE WHEN m.sender_id = v_me THEN m.receiver_id ELSE m.sender_id END as pid,
      m.content,
      m.created_at,
      m.read_at,
      m.sender_id,
      ROW_NUMBER() OVER (PARTITION BY (CASE WHEN m.sender_id = v_me THEN m.receiver_id ELSE m.sender_id END) ORDER BY m.created_at DESC) as rn
    FROM public.messages m
    WHERE m.sender_id = v_me OR m.receiver_id = v_me
  ),
  latest_per_partner AS (
    SELECT pm.pid, pm.content, pm.created_at
    FROM partner_msgs pm
    WHERE pm.rn = 1
  ),
  unread_per_partner AS (
    SELECT m.sender_id as pid, count(*) as unreads
    FROM public.messages m
    WHERE m.receiver_id = v_me AND m.read_at IS NULL
    GROUP BY m.sender_id
  )
  SELECT 
    l.pid as partner_id,
    coalesce(p.full_name, p.username, 'User') as name,
    p.username,
    p.email,
    p.avatar_url,
    p.member_code,
    p.last_seen_at,
    l.content as last_content,
    l.created_at as last_created_at,
    coalesce(u.unreads, 0)::BIGINT as unread_count
  FROM latest_per_partner l
  LEFT JOIN public.profiles p ON p.id = l.pid
  LEFT JOIN unread_per_partner u ON u.pid = l.pid
  ORDER BY l.created_at DESC;
end;
$$;

-- تفعيل RLS
ALTER TABLE public.admin_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_user_moderation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_message_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_known_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_login_logs ENABLE ROW LEVEL SECURITY;

-- سياسات RLS
DROP POLICY IF EXISTS admin_roles_read ON public.admin_roles;
CREATE POLICY admin_roles_read ON public.admin_roles FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.is_admin_caller());

DROP POLICY IF EXISTS admin_roles_modify ON public.admin_roles;
CREATE POLICY admin_roles_modify ON public.admin_roles FOR ALL TO authenticated
USING (public.is_admin_caller())
WITH CHECK (public.is_admin_caller());

DROP POLICY IF EXISTS profiles_select_all ON public.profiles;
CREATE POLICY profiles_select_all ON public.profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS profiles_insert_self ON public.profiles;
CREATE POLICY profiles_insert_self ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS profiles_update_admin_or_self ON public.profiles;
CREATE POLICY profiles_update_admin_or_self ON public.profiles FOR UPDATE TO authenticated
USING (auth.uid() = id OR public.is_admin_caller())
WITH CHECK (auth.uid() = id OR public.is_admin_caller());

DROP POLICY IF EXISTS messages_select_all_related ON public.messages;
CREATE POLICY messages_select_all_related ON public.messages FOR SELECT TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS messages_insert_user ON public.messages;
CREATE POLICY messages_insert_user ON public.messages FOR INSERT TO authenticated
WITH CHECK (
  auth.uid() = sender_id
  AND NOT EXISTS (
    SELECT 1 FROM public.admin_user_moderation aum
    WHERE aum.user_id = auth.uid() AND aum.is_banned = true
  )
);

DROP POLICY IF EXISTS messages_delete_owner_or_admin ON public.messages;
CREATE POLICY messages_delete_owner_or_admin ON public.messages FOR DELETE TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS messages_update_owner_or_admin ON public.messages;
CREATE POLICY messages_update_owner_or_admin ON public.messages FOR UPDATE TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller())
WITH CHECK (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS friend_requests_select ON public.friend_requests;
CREATE POLICY friend_requests_select ON public.friend_requests FOR SELECT TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS friend_requests_insert ON public.friend_requests;
CREATE POLICY friend_requests_insert ON public.friend_requests FOR INSERT TO authenticated
WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS friend_requests_update ON public.friend_requests;
CREATE POLICY friend_requests_update ON public.friend_requests FOR UPDATE TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller())
WITH CHECK (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS friend_requests_delete ON public.friend_requests;
CREATE POLICY friend_requests_delete ON public.friend_requests FOR DELETE TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR public.is_admin_caller());

DROP POLICY IF EXISTS user_identities_policy ON public.user_identities;
CREATE POLICY user_identities_policy ON public.user_identities FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.is_admin_caller());

DROP POLICY IF EXISTS admin_user_moderation_read ON public.admin_user_moderation;
CREATE POLICY admin_user_moderation_read ON public.admin_user_moderation FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.is_admin_caller());

DROP POLICY IF EXISTS admin_user_moderation_admin ON public.admin_user_moderation;
CREATE POLICY admin_user_moderation_admin ON public.admin_user_moderation FOR ALL TO authenticated
USING (public.is_admin_caller())
WITH CHECK (public.is_admin_caller());

DROP POLICY IF EXISTS admin_broadcasts_select ON public.admin_broadcasts;
CREATE POLICY admin_broadcasts_select ON public.admin_broadcasts FOR SELECT TO authenticated
USING (is_active = true OR public.is_admin_caller());

DROP POLICY IF EXISTS admin_broadcasts_admin ON public.admin_broadcasts;
CREATE POLICY admin_broadcasts_admin ON public.admin_broadcasts FOR ALL TO authenticated
USING (public.is_admin_caller())
WITH CHECK (public.is_admin_caller());

DROP POLICY IF EXISTS user_known_devices_self ON public.user_known_devices;
CREATE POLICY user_known_devices_self ON public.user_known_devices FOR ALL TO authenticated
USING (auth.uid() = user_id OR public.is_admin_caller());

DROP POLICY IF EXISTS user_login_logs_self ON public.user_login_logs;
CREATE POLICY user_login_logs_self ON public.user_login_logs FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.is_admin_caller());

-- الصلاحيات الدقيقة
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM anon;

GRANT USAGE ON SCHEMA public TO authenticated, anon;

GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT SELECT ON public.profiles TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.friend_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.user_identities TO authenticated;
GRANT SELECT ON public.admin_broadcasts TO authenticated;
GRANT SELECT ON public.admin_user_moderation TO authenticated;
GRANT SELECT ON public.admin_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.user_known_devices TO authenticated;
GRANT SELECT, INSERT ON public.user_login_logs TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

GRANT EXECUTE ON FUNCTION public.is_admin_caller() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_chat_messages(UUID, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_inbox_contacts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_all_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_ban(UUID, BOOLEAN, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_profile(UUID, TEXT, INTEGER, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_broadcast(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_purge_all_messages() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_admin(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_device_and_check_is_new(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
